### ISSUE TITLE
What I'm supposed to do here?

### ISSUE THREAD

**Issue by Antisa14200** [TheNewHEROBRINEX/Murder#17]
[Server thread/INFO] Enabling Murder v0.9
[Server thread/ERROR]: **Il mondo MurderHub non esiste. Cambia l'hub nelle config**
[Server thread/INFO]: Disabling Murder v0.9

**Comment by TheNewHEROBRINEX** [comment]
Open the config.yml and write the name of the world you want to use as
waiting lobby in the hub: line

Il 25 Dic 2017 2:48 PM, "Ante" <notifications@github.com> ha scritto:

[Server thread/INFO] Enabling Murder v0.9
[Server thread/ERROR]: *Il mondo MurderHub non esiste. Cambia l'hub nelle
config*
[Server thread/INFO]: Disabling Murder v0.9

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TheNewHEROBRINEX/Murder/issues/17>, or mute the thread

**Comment by Antisa14200** [comment]
Okay I did as you said and got this? 

 [Server thread/CRITICAL]: ErrorException: "yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 8, column 1), context while scanning a simple key (line 7, column 1)" (EXCEPTION) in "src/pocketmine/utils/Config" at line 155

**Comment by Antisa14200** [comment]
Well, got it solved by just renaming world to MurderMap

**Comment by TheNewHEROBRINEX** [comment]
You have to write exactly hub: worldname NOT hubworldname NOT hub:worldname

**Comment by Antisa14200** [comment]
Yeah ik, I renamed a world it works

**Comment by Antisa14200** [comment]
I got a error while doing hub: worldname
