### ISSUE TITLE
The skin of the players is changed

### ISSUE THREAD

**Issue by UnEnanoMas** [TheNewHEROBRINEX/Murder#60]
In dev 93, when players start the game, their skin is changed

**Comment by TheNewHEROBRINEX** [comment]
If the skin returns to normal at the end of the game, that's expected behaviour. Actually what should happen is that every player randomically gets a new skin and name (together referred to as identity) from files in a folder on disk, however for the moment I only shuffle the identities of the player in the arena between each other. This is done so that you can't know who is who, especially for when you play with your friends while on call on Discord or TeamSpeak.
